//
// Created by erasm on 9/04/2026.
//

#ifndef CREACIONLIBRERIAESTATICAUSANDOOTRA_ESTRUCTURAS_HPP
#define CREACIONLIBRERIAESTATICAUSANDOOTRA_ESTRUCTURAS_HPP

struct Persona {
    int edad;
    double salario;
};
#endif //CREACIONLIBRERIAESTATICAUSANDOOTRA_ESTRUCTURAS_HPP